/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GNOME 1.4 Configuration");
gchar *s = N_("Welcome to GNOME 1.4!  We have worked hard in the last  year, it kicks ass, all your base, yada yada.\n"
              "\n"
              "This tool will help you get started and get your desktop set us up the bomb.\n"
              "\n"
              "Click Next below to start illin'.");
gchar *s = N_("intro");
gchar *s = N_("Pick your poison");
gchar *s = N_("Use new configuration: Nautilus file manager and new themes");
gchar *s = N_("Select a custom configuration");
gchar *s = N_("Keep my current configuration");
gchar *s = N_("wheredoigo");
gchar *s = N_("Would you like to also reset your desktop icons and panel setup to the new defaults?");
gchar *s = N_("Reset my desktop icons");
gchar *s = N_("Reset my panel and applets");
gchar *s = N_("icons 1");
gchar *s = N_("label150");
gchar *s = N_("label151");
gchar *s = N_("label152");
gchar *s = N_("Use my existing panel configuration");
gchar *s = N_("panel");
gchar *s = N_("label150");
gchar *s = N_("label151");
gchar *s = N_("label152");
gchar *s = N_("Use my existing desktop manager");
gchar *s = N_("desktop");
gchar *s = N_("Please choose which icons you would like to have on your desktop:");
gchar *s = N_("New default icon set");
gchar *s = N_("My Nautilus icons (if Nautilus has been run before)");
gchar *s = N_("My GMC icons");
gchar *s = N_("icons 2");
gchar *s = N_("label150");
gchar *s = N_("label151");
gchar *s = N_("label152");
gchar *s = N_("Use my existing sawfish theme");
gchar *s = N_("sawfish");
gchar *s = N_("label150");
gchar *s = N_("label151");
gchar *s = N_("label152");
gchar *s = N_("Use my existing GTK+ theme");
gchar *s = N_("gtk");
gchar *s = N_("label150");
gchar *s = N_("label151");
gchar *s = N_("label152");
gchar *s = N_("Use my existing background");
gchar *s = N_("background");
gchar *s = N_("Someone set us up your config.");
gchar *s = N_("done");
